spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/demo
      
server:
  port: 8080
  
filepath:
  snapshotFileBasePath: C:\Users\neo\eclipse-workspace\demo\snapshot
  jFileBasePath: C:\Users\neo\eclipse-workspace\demo\journal